# Generated by Django 2.0.1 on 2018-01-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunefy_cms', '0002_auto_20180125_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, upload_to='upload/artists'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
