# Generated by Django 2.0.1 on 2018-01-30 11:47

from django.db import migrations, models
import tunefy_cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('tunefy_cms', '0003_auto_20180130_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='picture',
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to=tunefy_cms.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='artist',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='artists/thumbs'),
        ),
    ]
