# Generated by Django 2.0.1 on 2018-01-30 13:23

from django.db import migrations, models
import tunefy_cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('tunefy_cms', '0004_auto_20180130_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='artist',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=tunefy_cms.models.wrapper),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to=tunefy_cms.models.wrapper),
        ),
    ]
