# Generated by Django 2.0.1 on 2018-02-02 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunefy_cms', '0005_auto_20180130_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='all_artists',
            field=models.ManyToManyField(blank=True, related_name='_song_all_artists_+', to='tunefy_cms.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist+', to='tunefy_cms.Artist'),
        ),
    ]
