# Generated by Django 2.0.1 on 2018-02-03 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunefy_cms', '0006_auto_20180202_0517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('date_released',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('album', 'order', 'song')},
        ),
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='date_released',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='_album_genres_+', to='tunefy_cms.Genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
