# Generated by Django 2.0.1 on 2018-02-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunefy_cms', '0008_auto_20180205_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='all_artists',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='_song_artists_+', to='tunefy_cms.Artist'),
        ),
    ]
