# Generated by Django 2.0.1 on 2018-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunefy_cms', '0010_playlist_playlistelement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('popularity', 'album', 'order', 'song')},
        ),
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='track',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
