# Generated by Django 2.0.1 on 2018-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunefy_cms', '0012_playlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
